topic = "Usage of verbs Do and Make.";
grammar = "Use 'make' when you create or produce something<br>";
grammar+= "Use 'do' for actions: jobs, work, general activities you repeat often<br>";
cards = [
 {"question":"I ... a %arg1 for you",
  "answer": "made",
  "radios": ["made", "did"],
  "arg1": ["cake", "coctail", "present"],
 },
 {"question":"You ... too much noise",
  "answer": "make",
  "radios": ["make", "do"],
 },
 {"question":"Could you ... %arg1?",
  "answer": "make",
  "radios": ["make", "do"],
  "arg1": ["a comment", "a speech", "a suggestion"]
 },
 {"question":"Could you not ... %arg1?",
  "answer": "make",
  "radios": ["make", "do"],
  "arg1": ["this noise"]
 },
 {"question":"I ... my %arg1",
  "answer": "did",
  "radios": ["did", "made"],
  "arg1": ["homework", "housework", "chores", "job"],
 },
 {"question":"I ... %arg1",
  "answer": "did",
  "radios": ["did", "made"],
  "arg1": ["something", "nothing", "everything"],
 },
 {"question":"I will ... %arg1 for you",
 "answer": "do",
 "radios": ["do", "make"],
 "arg1": ["anything"],
 },
 {"question":"I have already ... plans for the upcoming weekend",
  "answer": "made",
  "radios": ["made", "did"]
 },
 {"question":"I ... a %arg1",
  "answer": "made",
  "radios": ["made", "did"],
  "arg1": ["decision", "plan", "choice"]
 },
 {"question":"We ... %arg1",
  "answer": "made",
  "radios": ["made", "did"],
  "arg1": ["an arrangement"]
 },
 
 {"question":"Have you ... the dishes yet?",
  "answer": "done",
  "radios": ["done", "made"],
  "comment": "done=washed"
 },
 {"question":"I'll ... the lawns, if you ... the kitchen",
  "answer": "do",
  "radios": ["make", "do"],
  "comment": "do the lawns=mow, do the kitchen=clean"
 },
 {"question":"This building is ... of concrete",
  "answer": "made",
  "radios": ["made", "did"],
  "comment": "passive voice"
 },
 {"question":"This watchtower is ... from wood",
  "answer": "made",
  "radios": ["made", "did"],
  "comment": "passive voice"
 },
 {"question":"This PC ... in PRC",
 "answer": "made",
 "radios": ["made", "did"],
 "comment": "passive voice"
 },
 {"question":"This present is ... by me",
 "answer": "made",
 "radios": ["made", "did"],
 },
  {"question":"She ... me happy",
  "answer": "made",
  "radios": ["made", "did"],
 },
 {"question":"Onions always ... your eyes water",
  "answer": "make",
  "radios": ["make", "do"],
 },
 {"question":"You always ... me happy",
  "answer": "make",
  "radios": ["do", "make"],
 },
 {"question":"It's not his fault. I ... him do it!",
  "answer": "made",
  "radios": ["made", "did"],
 },
 {"question":"Have you ... your homework?",
  "answer": "done",
  "radios": ["made", "done"],
 },
 {"question":"I %arg1 ... this job",
  "answer": "do",
  "radios": ["do", "make"],
  "arg1": ["won't", "wouldn't like to"],
 },
 {"question":"Don't just stare – ... something!",
  "answer": "do",
  "radios": ["do", "make"],
 },
 {"question":"Is there anything I could ... to help you?",
  "answer": "do",
  "radios": ["do", "make"],
 },
 {"question":"Can you ... %arg1?",
  "answer": "make",
  "radios": ["do", "make"],
  "arg1": ["a call", "a promise"],
 },
 {"question":"I ... %arg1?",
  "answer": "made",
  "radios": ["did", "made"],
  "arg1": ["dinner", "a cocktail", "a cup of tea"],
 },
 {"question":"Can you ... %arg1?",
  "answer": "do",
  "radios": ["do", "make"],
  "arg1": ["a course", "a crossword", "a dance", "a drawing of this house", 
"a fart", "a favour", "a favor", "a painting", "a project", "a service",
"an assignment", "anything", "business", "chores", "damage to the boss",
"harm to yourself", "exercises", "good", "badly", "nothing", "research",
"right", "the right thing", "something", "the dishes", "the gardening",
"the housework", "the ironing", "the laundry", "the rest", "the shopping",
"the wasshing", "well", "wrong", "the wrong thing", "your best",
"your homework", "your nails", "your work"]},
 {"question":"Can you ... %arg1?",
  "answer": "make",
  "radios": ["do", "make"],
  "arg1": ["a cake", "a bet", "a call", "a change", "a choice", "a comment",
"a complaint", "a confession", "a connection", "a cup of tea", "a cup of coffee",
"a date", "a decision", "a demand", "a difference", "a discovery", "a face",
"a fool of yourself", "a fortune", "a friend", " a fuss", "a joke", "a line",
"a list", "a loss", " a mess", " a mistake", "a noise", 
"a pass at someone (to do or say something that clearly shows one wants to begin a romantic or sexual relationship with (someone))",
"a phone call", "a plan", "a point", "a prediction", "a profit", "a promise",
"a reservation", "a sandwich", "a scene", "a sound", "a speech", "a statement",
"a suggestion", "advances", "alterations", "an appointment", "an announecement",
"an attempt", "an effort", "an error", "an escape", "an exception", "an excuse",
"an impression", "an observation", "an offer", "amends", "arrangements", "breakfast",
"certain", "clear", "dinner", "faces", "famous", "fun of someone", "love", "lunch",
"inquiries", "peace", "possible", "progress", "money", "room", "sales", "sense",
"someone rich", "someone smile", "sure", "trouble", "war", "your bed", 
"your mind up", "your way"]},
]


include("js/engine.js",function(){
  //
});
