topic = "Irregular verbs. Write 2nd and 3rd forms of a verb.";
cards = [
 {"question":"be",
  "answer": ["was been", "were been"],
  "radios": [],
  "arg1": []},
 {"question":"bear",
  "answer": ["bore", "borne"],
  "radios": [],
  "arg1": []},
 {"question":"beat",
  "answer": ["beat", "beaten"],
  "radios": [],
  "arg1": []},
 {"question":"become",
  "answer": "became become",
  "radios": [],
  "arg1": []},
 {"question":"begin",
  "answer": "began begun",
  "radios": [],
  "arg1": []},
 {"question":"bend",
  "answer": ["bent", "bent"],
  "radios": [],
  "arg1": []},
 {"question":"bet",
  "answer": ["bet", "bet"],
  "radios": [],
  "arg1": []},
 {"question":"bind",
  "answer": ["bound", "bound"],
  "radios": [],
  "arg1": []},
 {"question":"bite",
  "answer": ["bit", "bitten"],
  "radios": [],
  "arg1": []},
 {"question":"bleed",
  "answer": "bled bled",
  "radios": [],
  "arg1": []},
 {"question":"blow",
  "answer": "blew blown",
  "radios": [],
  "arg1": []},
 {"question":"break",
  "answer": "broke broken",
  "radios": [],
  "arg1": []},
 {"question":"bring",
  "answer": "brought brought",
  "radios": [],
  "arg1": []},
 {"question":"build",
  "answer": "built built",
  "radios": [],
  "arg1": []},
 {"question":"burn",
  "answer": "burnt burnt",
  "radios": [],
  "arg1": []},
 {"question":"burst",
  "answer": ["burst", "burst"],
  "radios": [],
  "arg1": []},
 {"question":"buy",
  "answer": "bought bought",
  "radios": [],
  "arg1": []},
 {"question":"cast",
  "answer": "cast cast",
  "radios": [],
  "arg1": []},
  {"question":"choose",
  "answer": "chose choosen",
  "radios": [],
  "arg1": []},
 {"question":"come",
  "answer": "came come",
  "radios": [],
  "arg1": []},
 {"question":"cost",
  "answer": "cost cost",
  "radios": [],
  "arg1": []},
 {"question":"cut",
  "answer": "cut cut",
  "radios": [],
  "arg1": []},
 {"question":"do",
  "answer": "did done",
  "radios": [],
  "arg1": []},
 {"question":"draw",
  "answer": "drew drawn",
  "radios": [],
  "arg1": []},
 {"question":"dream",
  "answer": ["dreamt dreamt","dream dream"],
  "radios": [],
  "arg1": []},
 {"question":"drink",
  "answer": "drank drunk",
  "radios": [],
  "arg1": []},
 {"question":"drive",
  "answer": "drove driven",
  "radios": [],
  "arg1": []},
 {"question":"eat",
  "answer": "ate eaten",
  "radios": [],
  "arg1": []},
 {"question":"fall",
  "answer": "fell fallen",
  "radios": [],
  "arg1": []},
 {"question":"feel",
  "answer": "felt felt",
  "radios": [],
  "arg1": []},
 {"question":"fight",
  "answer": "fought fought",
  "radios": [],
  "arg1": []},
 {"question":"find",
  "answer": "found found",
  "radios": [],
  "arg1": []},
 {"question":"fly",
  "answer": "flew flown",
  "radios": [],
  "arg1": []},
 {"question":"forbid",
  "answer": "forbade forbidden",
  "radios": [],
  "arg1": []},
 {"question":"get",
  "answer": "got got",
  "radios": [],
  "arg1": []},
 {"question":"give",
  "answer": "gave given",
  "radios": [],
  "arg1": []},
 {"question":"go",
  "answer": "went gone",
  "radios": [],
  "arg1": []},
 {"question":"grow",
  "answer": "grew grown",
  "radios": [],
  "arg1": []},
 {"question":"have",
  "answer": "had had",
  "radios": [],
  "arg1": []},
 {"question":"hear",
  "answer": "heard heard",
  "radios": [],
  "arg1": []},
 {"question":"hide",
  "answer": "hid hidden",
  "radios": [],
  "arg1": []},
 {"question":"hit",
  "answer": "hit hit",
  "radios": [],
  "arg1": []},
 {"question":"hold",
  "answer": "held held",
  "radios": [],
  "arg1": []},
 {"question":"hurt",
  "answer": "hurt hurt",
  "radios": [],
  "arg1": []},
 {"question":"keep",
  "answer": "kept kept",
  "radios": [],
  "arg1": []},
 {"question":"know",
  "answer": "knew known",
  "radios": [],
  "arg1": []},
 {"question":"learn",
  "answer": ["learnt learnt","learned learned"],
  "radios": [],
  "arg1": [],
  "comment": "learnt learnt UK, learned learned US",
  "minor": "yes"},
 {"question":"leave",
  "answer": "left left",
  "radios": [],
  "arg1": []},
 {"question":"let",
  "answer": "let let",
  "radios": [],
  "arg1": []},
 {"question":"lie (on a table)",
  "answer": "lay lain",
  "radios": [],
  "arg1": []},
 {"question":"lie (to person)",
  "answer": "lied lied",
  "radios": [],
  "arg1": []},
 {"question":"lose",
  "answer": "lost lost",
  "radios": [],
  "arg1": []},
 {"question":"make",
  "answer": "made made",
  "radios": [],
  "arg1": []},
 {"question":"mean",
  "answer": "meant meant",
  "radios": [],
  "arg1": []},
 {"question":"meet",
  "answer": "met met",
  "radios": [],
  "arg1": []},
 {"question":"pay",
  "answer": "paid paid",
  "radios": [],
  "arg1": []},
 {"question":"put",
  "answer": "put put",
  "radios": [],
  "arg1": []},
 {"question":"read",
  "answer": "read read",
  "radios": [],
  "arg1": []},
 {"question":"ride",
  "answer": "rode ridden",
  "radios": [],
  "arg1": []},
 {"question":"run",
  "answer": "ran run",
  "radios": [],
  "arg1": []},
 {"question":"say",
  "answer": "said said",
  "radios": [],
  "arg1": []},
 {"question":"see",
  "answer": "saw seen",
  "radios": [],
  "arg1": []},
 {"question":"sell",
  "answer": "sold sold",
  "radios": [],
  "arg1": []},
 {"question":"send",
  "answer": "sent sent",
  "radios": [],
  "arg1": []},
 {"question":"show",
  "answer": "showed shown",
  "radios": [],
  "arg1": []},
 {"question":"sing",
  "answer": "sang sung",
  "radios": [],
  "arg1": []},
 {"question":"sleep",
  "answer": "slept slept",
  "radios": [],
  "arg1": []},
 {"question":"speak",
  "answer": "spoke spoken",
  "radios": [],
  "arg1": []},
 {"question":"spell",
  "answer": "spelt spelt",
  "radios": [],
  "arg1": []},
 {"question":"stand",
  "answer": "stood stood",
  "radios": [],
  "arg1": []},
 {"question":"steal",
  "answer": "stole stolen",
  "radios": [],
  "arg1": []},
 {"question":"swim",
  "answer": "swam swum",
  "radios": [],
  "arg1": []},
 {"question":"take",
  "answer": "took taken",
  "radios": [],
  "arg1": []},
 {"question":"teach",
  "answer": "taught taught",
  "radios": [],
  "arg1": []},
 {"question":"tell",
  "answer": "told told",
  "radios": [],
  "arg1": []},
 {"question":"think",
  "answer": "thought thought",
  "radios": [],
  "arg1": []},
 {"question":"throw",
  "answer": "threw thrown",
  "radios": [],
  "arg1": []},
 {"question":"wake",
  "answer": "woke woken",
  "radios": [],
  "arg1": []},
 {"question":"wear",
  "answer": "wore worn",
  "radios": [],
  "arg1": []},
 {"question":"win",
  "answer": "won won",
  "radios": [],
  "arg1": []},
 {"question":"write",
  "answer": "wrote written",
  "radios": [],
  "arg1": []},
]


include("js/engine.js",function(){
  //
});
