topic = "In/on time, at/in the end.";
cards = [
 {"question":"The 11:30 %arg1 left ... time",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["bus", "train", "flight"],
 },
 {"question":"Let's meet at 21:30. Ok, please be ... time",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": []
 },
 {"question":"We %arg1 ... time",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["started", "finished"]
 },
 {"question":"Will you be home ... time for %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["dinner", "Christmas Eve"]
 },
 {"question":"I sent her a present. I hope it arrives ... time",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": []
 },
 {"question":"I want to get home ... time to %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["see the footbal"]
 },
 {"question":"Pushkin was born ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["June 6, 1799"]
 },
 {"question":"We got here just ... time %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["to catch the train", "to catch the bus"],
 },
 {"question":"I'm going away ... the end of %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["my contract", "May", "Summer"],
 },
 {"question":"... the end of performance, there was %arg1 appluase",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["long", "great", "loud"],
 },
 {"question":"Contesters shook ... the end of the match",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": [],
 },
 {"question":"He came here ... the beginning of %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["January", "Febrary", "March", "April", "May", "June", "July", 
    "August", "September", "October", "November", "December",
    "winter", "spring", "summer", "autumn", "fall"], 
 },
 {"question":"... the end we %arg1 it",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["sold", "bought", "made"],
 },
]


include("js/engine.js",function(){
  //
});
