topic = "Prepositions with verbs.";
grammar = "(Have a ) look/stare/glance AT<br>";
grammar+= "Laugh/smile AT<br>";
grammar+= "Aim/point (smth) AT, shoot/fire (smth) AT<br>";
grammar+= "Talk/speak TO (WITH possible) smb<br>";
grammar+= "Listen/write TO, invite TO<br>";
grammar+= "But: phone/telephone/telegramm(?) smb (no article!)<br>"; 
grammar+= "Shout AT smb, when you angry<br>";
grammar+= "Shout TO smb, when you trying attract/signal/communicate with them<br>";
grammar+= "Throw smth AT smd (to hit), throw smth TO smbd (to catch)<br>";
grammar+= "Explain/describe/apologise TO smb<br>";
grammar+= "But: thank smb (no article!), ask smb (no article!)<br>";

cards = [
 {"question":"Look ... her! She is so gorgeous",
  "answer": "at",
  "radios": ["at", "to", "on"],
 },
 {"question":"A cat stared ... food until I fed the cat",
  "answer": "at",
  "radios": ["at", "to", "on"],
 },
 {"question":"I glanced ... the question and shouted the answer",
  "answer": "at",
  "radios": ["at", "to", "on", "over"],
 },
 {"question":"She never came. She laughted ... the weirdo",
  "answer": "at",
  "radios": ["at", "to", "on"],
 },
 {"question":"He %arg1 the gun ... him",
  "answer": "at",
  "radios": ["at", "to", "on"],
  "arg1": ["aimed", "pointed"],
 },
 {"question":"He %arg1 ... ducks",
  "answer": "at",
  "radios": ["at", "to", "on"],
  "arg1": ["shot", "fired"],
 },
 {"question":"I talked ... my father yesterday",
  "answer": ["to","with"],
  "radios": ["at", "to", "on"],
  "comment": "WITH is acceptable, but TO is preferrable!",
  "minor": "yes",
 },
 {"question":"A baby listened ... the lullaby",
  "answer": "to",
  "radios": ["at", "to", "on"],
 },
 {"question":"I wrote an enquery ... the company",
  "answer": "to",
  "radios": ["at", "to", "on"],
 },
 {"question":"Dell? I work ... the company",
  "answer": "at",
  "radios": ["at", "to", "on"],
 },
 {"question":"I invited them ... the party",
  "answer": "to",
  "radios": ["at", "to", "on"],
 },
 {"question":"You need to %arg1 ... him now!",
  "answer": ["","no preposition"],
  "radios": ["at", "to", "on", "no preposition"],
  "arg1": ["phone", "telephone", "call", "telegramm"],
 },
 {"question":"She shouted... him with angry face",
  "answer": "at",
  "radios": ["at", "to", "on"],
 },
 {"question":"She shouted ... him: 'faster'",
  "answer": "to",
  "radios": ["at", "to", "on"],
 },
 {"question":"I threw a knife ... the target, and hit 10",
  "answer": "at",
  "radios": ["at", "to", "on"],
 },
 {"question":"I threw a hook ... the friends' supboard",
  "answer": "to",
  "radios": ["at", "to", "on"],
 },
 {"question":"Explain ... the guest how to use the boiler",
  "answer": "to",
  "radios": ["at", "to", "on"],
 },
 {"question":"Describe the look of the thief ... the officer ",
  "answer": "to",
  "radios": ["at", "to", "on"],
 },
 {"question":"Describe ... the officer how the thief looks",
  "answer": "to",
  "radios": ["at", "to", "on"],
 },
 {"question":"Thanks ... God, I survived",
  "answer": ["","no preposition"],
  "radios": ["at", "to", "on", "no preposition"],
 },
 {"question":"Ask ... him about the game",
  "answer": ["","no preposition"],
  "radios": ["at", "from", "on", "no preposition"],
 },

]

include("js/engine.js",function(){
  //
});
