cards = [
 {"question":"We are gonna have a party ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
 },
 {"question":"We are going at home ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["Christmas", "Thanksgiving day", "Easter", "Independence Day"],
 },
 {"question":"We have called to arms ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["24 February", "22 September", "22 Sep. 2022", "24 Feb. 2022"],
 },
 {"question":"I got a new lego ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["my birthday", "on New Year's Eve", "on Christmas' Eve"],
 },
 {"question":"We got married ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["May", "Summer", "2022"],
 },
 {"question":"We made this ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the 2010s", "the last century"],
 },
 {"question":"Humankind invented this ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the Ice Age", "the Bronze Age", "the last century"],
 },
 {"question":"We made it ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["in the past"],
 },
 {"question":"We hope to achieve it ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the future", "the next century"],
 },
]
