cards = [
 {"question":"We are gonna have a party ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
 },
 {"question":"We play cards ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["Saturday evenings", "Sunday evenings", "Friday evenings"]
 },
 {"question":"We have English lessons ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["Monday evenings", "Wednesday evenings"]
 },
 {"question":"We play basketball ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["Saturday afternoons", "Sunday afternoons"]
 },
 {"question":"We make pancakes ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["Saturday mornings", "Sunday mornings"]
 },
 {"question":"We play basketball ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["Saturday afternoons", "Sunday afternoons"]
 },
 {"question":"We are going at home ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["Christmas", "Thanksgiving day", "Easter", "Independence Day"],
 },
 {"question":"We were called to arms ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["24 February", "22 September", "22 Sep. 2022", "24 Feb. 2022"],
 },
 {"question":"I got a new lego ... %arg1",
  "answer": "on",
  "radios": ["on", "at", "in"],
  "arg1": ["my birthday", "on New Year's Eve", "on Christmas' Eve"],
 },
 {"question":"We got married ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["May", "Summer", "2022"],
 },
 {"question":"We did it ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the morning", "the afternoon", "the evening"],
 },
 {"question":"We do that ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the mornings", "the afternoons", "the evenings"],
 },
 {"question":"We made this ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the 2010s", "the last century"],
 },
 {"question":"Humankind invented this ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the Ice Age", "the Bronze Age", "the last century"],
 },
 {"question":"We made it ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the past"],
 },
 {"question":"We hope to achieve it ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the future", "the next century"],
 },
 {"question":"We hope to achieve it ... %arg1",
  "answer": "in",
  "radios": ["on", "at", "in"],
  "arg1": ["the future", "the next century"],
 },
 {"question":"We usually drink tea ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["3 o'clock", "5 o'clock"],
 },
 {"question":"We have a daily meeting ... %arg1. Don't be late!",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["11 o'clock", "10:30am"],
 },
 {"question":"I like to take a nap ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["dinnertime"],
 },
 {"question":"We are gonna ride today ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["noon", "sunrise", "sunset"],
 },
 {"question":"I read fairytales to my children ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["bedtime"],
 },
 {"question":"I couldn't help you ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["the moment"],
 },
 {"question":"I couldn't help you ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["the moment"],
 },
 {"question":"I couldn't help you ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["the moment"],
 },
 {"question":"I usually write articles ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["the weekened"],
 },
 {"question":"Stars shines ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["night"],
 },
 {"question":"Stars shine ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["night"],
 },
 {"question":"Knock-knock. Who is there? The Wolf. Is The Pig home ... %arg1?",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["the present moment", "present"],
 },
 {"question":"We finished ... %arg1",
  "answer": "at",
  "radios": ["on", "at", "in"],
  "arg1": ["the same time"],
 },

]
